### ISSUE TITLE
The SpartQA dataset link seems to be broken

### ISSUE THREAD

**Issue by RobBlackwell** [HLR/SpartQA-baselines#3]
When I click the link in `Readme.md` to download the spartQA dataset, Google Drive reports "Sorry, the file you have requested does not exist."

I would like to make use of your benchmark data and perhaps try to reproduce your results. Please could you reshare the link?

**Comment by kordjamshidi** [comment]
Please see the Data bar on this page, you will see all the information for download: https://www.cse.msu.edu/~kordjams/SpRL.htm, please let me know if something is missing. Thanks.

**Comment by RobBlackwell** [comment]
Thanks!
